import Head from "next/head"
import ContainerLayout from "../../layout/ContainerLayout/ContainerLayout"

const ContactUs = () => {
  return (
    <ContainerLayout bgColor={'green'}>
      <Head>
        <title>ContactUs</title>
        <meta name="description" content="Generated by united chauffeur" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>ContactUs</h1>
    </ContainerLayout>
  )
}

export default ContactUs