import Head from "next/head"
import ContainerLayout from "../../layout/ContainerLayout/ContainerLayout"

const Features = () => {
  return (
    <ContainerLayout bgColor={'salmon'}>
      <Head>
        <title>Features</title>
        <meta name="description" content="Generated by united chauffeur" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>Features</h1>
    </ContainerLayout>
  )
}

export default Features