
import Head from 'next/head'
import ContainerLayout from '../../layout/ContainerLayout/ContainerLayout'

const ServiceRates = () => {
  return (
   <ContainerLayout bgColor={'blue'}>
     <Head>
        <title>ServiceRates</title>
        <meta name="description" content="Generated by united chauffeur" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <h1>ServiceRates</h1>
   </ContainerLayout>
  )
}

export default ServiceRates