import Head from 'next/head'
import ContainerLayout from '../layout/ContainerLayout/ContainerLayout'

export default function Home() {
  return (
    <>
       <ContainerLayout bgColor='black'>
       <Head>
        <title>Home</title>
        <meta name="description" content="Generated by united chauffeur" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>Home</h1>
       </ContainerLayout>
    </>
  )
}
