import React from 'react'
import ContainerLayout from '../../layout/ContainerLayout/ContainerLayout'

const AboutUs = () => {
  return (
   <ContainerLayout bgColor={'gray'}>
    <Head>
        <title>AboutUs</title>
        <meta name="description" content="Generated by united chauffeur" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1>AboutUs</h1>
   </ContainerLayout>
  )
}

export default AboutUs