import ContainerLayout from "../../layout/ContainerLayout/ContainerLayout"

const OurFleet = () => {
  return (
   <ContainerLayout bgColor={'purple'}>
    <Head>
        <title>OurFleet</title>
        <meta name="description" content="Generated by united chauffeur" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1>OurFleet</h1>
   </ContainerLayout>
  )
}

export default OurFleet